//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChiypesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public int GenderId { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public System.DateTime AddDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
