//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChiypesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.ProductCountry = new HashSet<ProductCountry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<ProductCountry> ProductCountry { get; set; }
    }
}
