//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChiypesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> StatusOrderId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
