//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChiypesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductCountry = new HashSet<ProductCountry>();
            this.ProductIntakeProduct = new HashSet<ProductIntakeProduct>();
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public byte[] Photo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int UnitId { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductCountry> ProductCountry { get; set; }
        public virtual ICollection<ProductIntakeProduct> ProductIntakeProduct { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
