//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChiypesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIntake
    {
        public ProductIntake()
        {
            this.ProductIntakeProduct = new HashSet<ProductIntakeProduct>();
        }
    
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<ProductIntakeProduct> ProductIntakeProduct { get; set; }
    }
}
