//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChiypesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual User User { get; set; }
    }
}
